### ISSUE TITLE
Version 2 Development

### ISSUE THREAD

**Issue by kvnrynfl** [kvnrynfl/Discord-Bot#5]
## Discord Bot "Version 2 Development" with MongoDB
This is the second version of the Discord Bot that is currently in development. In this version, all the SQL queries have been replaced with MongoDB queries to improve performance and reliability. 

### The administrator features that have been added include:
- [x] `/ban temporary [user] [duration] [reason]` - provides a feature to temporarily ban a user from the server.
- [x] `/ban permanent [user] [reason]` - provides a feature to permanently ban a user from the server.
- [x] `/ban check [userId]` - provides a feature to check if a user is banned or not.
- [x] `/ban list` - provides a feature to list all banned users on the server.
- [x] `/unban [userId] [reason]` - provides a feature to unban a user from the server.
- [x] `/kick [target] [reason]` - provides a feature to kick a user from the server.
- [x] `/mute [target] [reason] [duration]` - provides a feature to mute a user, so they can't send messages on the server.
- [x] `/unmute [target] [reason]` - provides a feature to cancel the mute of a user.
- [x] `/role add [user] [role]` - provides a feature to add a role to a user.
- [x] `/role remove [user] [role]` - provides a feature to remove a role from a user.
- [x] `/role check [user]` - provides a feature to check the roles of a user.
- [x] `/nick [user] [nickname]` - provides a feature to change the nickname of a user.
- [x] `/poll [channel] [title] [description]` - provides a feature to create a poll and get votes from users.

### The general features that have been added include:
- [x] `/weather [city name]` - provides weather information for a specific city.
- [x] `/quotes` - provides a feature to send a motivational or inspirational quote.

### The music features that have been added include:
- [x] `/queue swap [index1] [index2]` - moves the position of two songs in the music queue.
- [x] `/queue move [index1] [index2]` - moves the position of one song from index1 to index2 in the music queue.

**Comment by serzhan181** [comment]
Since it is the second version, maybe it is also good to make it in typescript? What do you think?

**Comment by kvnrynfl** [comment]
> Since it is the second version, maybe it is also good to make it in typescript? What do you think?

My answer is no, I am not in favor of using Typescript for the second version. I think it would take me a lot of time to become proficient in it. Instead, I prefer to use Javascript and utilize node modules that have already been developed by others.
